-- door_lcd.sql
-- Creates tables: door, lcd
-- Based on JPA entities: Door, Lcd (both reference microcontroller.mc_id)

-- Assumes table microcontroller(mc_id) already exists.

CREATE TABLE IF NOT EXISTS door (
    door_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    is_opened BOOLEAN DEFAULT FALSE,
    mc_id     INT NOT NULL,

    CONSTRAINT fk_door_microcontroller
        FOREIGN KEY (mc_id) REFERENCES microcontroller (mc_id)
);

CREATE INDEX IF NOT EXISTS idx_door_mc_id ON door (mc_id);


CREATE TABLE IF NOT EXISTS lcd (
    lcd_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255),
    display VARCHAR(255),
    mc_id   INT NOT NULL,

    CONSTRAINT fk_lcd_microcontroller
        FOREIGN KEY (mc_id) REFERENCES microcontroller (mc_id)
);

CREATE INDEX IF NOT EXISTS idx_lcd_mc_id ON lcd (mc_id);

Insert into door (name, is_opened, mc_id) values ('Main Entrance', true, 1);
Insert into door (name, is_opened, mc_id) values ('Exit', true, 1);
Insert into lcd (name, display, mc_id) values ('Lobby Display', 'Welcome to Raumanian', 1);
