DROP TABLE IF EXISTS "users", "parking_space", "user_parking_space", "microcontroller", "slot", "sensor", "rfid", "entry_log", "door", "lcd";

CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar UNIQUE NOT NULL,
                         "email" varchar UNIQUE NOT NULL,
                         "password_hash" varchar NOT NULL,
                         "role" varchar NOT NULL,
                         "enabled" boolean DEFAULT true,
                         "created_at" timestamp
);

CREATE TABLE "parking_space" (
                                 "ps_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "name" varchar,
                                 "location" varchar,
                                 "owner" varchar NOT NULL
);

CREATE TABLE "user_parking_space" (
                                      "user_id" int NOT NULL,
                                      "ps_id" int NOT NULL,
                                      PRIMARY KEY ("user_id", "ps_id")
);

CREATE TABLE "microcontroller" (
                                   "mc_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "mc_code" varchar UNIQUE NOT NULL,
                                   "name" varchar,
                                   "online" boolean DEFAULT false,
                                   "uptime_sec" bigint,
                                   "last_seen" timestamp,
                                   "ps_id" int NOT NULL
);

CREATE TABLE "door" (
                         "door_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar UNIQUE,
                         "is_opened" boolean DEFAULT FALSE,
                         "mc_id" int NOT NULL
);

CREATE TABLE "lcd" (
                        "lcd_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar UNIQUE,
                        "display" text,
                        "mc_id" int NOT NULL
);

CREATE TABLE "sensor" (
                          "sensor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar UNIQUE,
                          "type" varchar,
                          "slot_id" int NOT NULL,
                          "mc_id" int NOT NULL
);

CREATE TABLE "slot" (
                        "slot_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar UNIQUE,
                        "ps_id" int NOT NULL,
                        "is_occupied" boolean DEFAULT false
);

CREATE TABLE "rfid" (
                        "rfid_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "rfid_code" varchar UNIQUE NOT NULL,
                        "ps_id" int NOT NULL,
                        "currently_used" boolean DEFAULT false
);

CREATE TABLE "entry_log" (
                             "log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "rfid_id" int NOT NULL,
                             "license_plate" varchar,
                             "license_plate_image_key" varchar,
                             "in_time" timestamp,
                             "out_time" timestamp
);

COMMENT ON COLUMN "users"."role" IS 'ROLE_USER | ROLE_ADMIN';
ALTER TABLE "user_parking_space"
    ADD CONSTRAINT "fk_user_parking_space_user"
        FOREIGN KEY ("user_id") REFERENCES "users" ("user_id")
            ON DELETE CASCADE;

ALTER TABLE "user_parking_space"
    ADD CONSTRAINT "fk_user_parking_space_ps"
        FOREIGN KEY ("ps_id") REFERENCES "parking_space" ("ps_id")
            ON DELETE CASCADE;

ALTER TABLE "microcontroller"
    ADD CONSTRAINT "fk_microcontroller_ps"
        FOREIGN KEY ("ps_id") REFERENCES "parking_space" ("ps_id")
            ON DELETE CASCADE;

ALTER TABLE "door"
    ADD CONSTRAINT "fk_door_mc"
        FOREIGN KEY ("mc_id") REFERENCES "microcontroller" ("mc_id")
            ON DELETE CASCADE;

ALTER TABLE "lcd"
    ADD CONSTRAINT "fk_lcd_mc"
        FOREIGN KEY ("mc_id") REFERENCES "microcontroller" ("mc_id")
            ON DELETE CASCADE;

ALTER TABLE "sensor"
    ADD CONSTRAINT "fk_sensor_slot"
        FOREIGN KEY ("slot_id") REFERENCES "slot" ("slot_id")
            ON DELETE CASCADE;

ALTER TABLE "sensor"
    ADD CONSTRAINT "fk_sensor_mc"
        FOREIGN KEY ("mc_id") REFERENCES "microcontroller" ("mc_id")
            ON DELETE CASCADE;

ALTER TABLE "slot"
    ADD CONSTRAINT "fk_slot_ps"
        FOREIGN KEY ("ps_id") REFERENCES "parking_space" ("ps_id")
            ON DELETE CASCADE;

ALTER TABLE "rfid"
    ADD CONSTRAINT "fk_rfid_ps"
        FOREIGN KEY ("ps_id") REFERENCES "parking_space" ("ps_id")
            ON DELETE CASCADE;

ALTER TABLE "entry_log"
    ADD CONSTRAINT "fk_entry_log_rfid"
        FOREIGN KEY ("rfid_id") REFERENCES "rfid" ("rfid_id")
            ON DELETE CASCADE;
